      # Checkout source repo (with theme submodule)
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Setup Hugo
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Build site
      - run: hugo --minify

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_repo: ikmakinen/ikmakinen.github.io
          force_orphan: true